# Generated by Django 5.1.4 on 2025-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='uploads/default-avatar-profile-icon-vector-social-media-user-image-182145777.jpg', upload_to='uploads/profile'),
        ),
    ]
